#+TITLE: header-progress

Header line based minimal progress indicators for Emacs. See this [[https://lepisma.xyz/journal/2024/10/27/header-progress-bar/index.html][blog post]] for
screen casts.

* Installation
#+begin_src emacs-lisp
  (use-package header-progress
    :vc (:fetcher github :repo lepisma/header-progress))
#+end_src

* Usage
The core construct here is the idea of a /bar function/ that returns a string
depicting progress of any kind which can be used like the following:

#+begin_src emacs-lisp
  ;; To start displaying the progress bar
  (hp-bar-start #'bar-function)

  ;; Do work

  ;; Once the work is done (or the need of bar is over), call
  (hp-bar-finish)
#+end_src

** Bar Functions
A bar function has to return string that directly gets set as
~header-line-format~. The call to this function is managed by Emacs whenever it
decides to update the bar. This might not give you extremely precise control but
in has worked for me in practice.

There are the following bar functions available in the package as of now. Both
return bars that look something like this:

#+begin_src shell
█████████——————————
#+end_src

1. ~hp-progress-bar~: This is a general bar that uses the current value of
   ~hp-ratio~ to update the bar. Since the header line is not updated in tightly
   running lisp code, you might get more mileage from this in async programs.
2. ~hp-buffer-progress-bar~: This displays position in buffer. This respects
   narrowing so you might not get what you want when using this in org based
   presentations like via [[https://github.com/rlister/org-present][org-present]].
3. ~hp-buffer-progress-bar-wide~: Similar to previous but computes buffer progress
   on the full buffer instead of narrowed region.
4. ~hp-indeterminate-bar~: For progress indication where point of completion is
   unknown. See this example for usage:

#+begin_src emacs-lisp
  ;; Pregenerate the gradient patch for display
  (setq hp-gradient-patch (generate-wrapping-gradient-patch "#6ad8ff" "#5856d6" 100))
  (hp-bar-start #'hp-indeterminate-bar)
  (hp-bar-finish)
#+end_src

You can, of course, make your own functions and substitute.

*** Customizing
The looks of bars can be customized by tweaking the following:

- ~hp-bar-complete-face~
- ~hp-bar-remaining-face~
- ~hp-bar-complete-char~
- ~hp-bar-remaining-char~
